name: Chicago Blues Central
favicon: null
layout_spectrum: 0.7315315606538206
typography_spectrum: 0.47667193436063826
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.548949874471873
  lightness: 0.4280512109398842
  saturation: 0.7041288611944765
  rhythmicContrast: 0.3440508807543665
purpose: []
